
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
Prisma.prismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  banned: 'banned',
  banReason: 'banReason',
  banExpires: 'banExpires'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  impersonatedBy: 'impersonatedBy'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  docId: 'docId',
  birthdate: 'birthdate',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankScalarFieldEnum = {
  id: 'id',
  name: 'name',
  accountNo: 'accountNo',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  type: 'type',
  sku: 'sku',
  name: 'name',
  description: 'description',
  price: 'price',
  cost: 'cost',
  commissionPercent: 'commissionPercent',
  categoryId: 'categoryId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SaleScalarFieldEnum = {
  id: 'id',
  saleNumber: 'saleNumber',
  createdById: 'createdById',
  customerId: 'customerId',
  currency: 'currency',
  subtotal: 'subtotal',
  discountTotal: 'discountTotal',
  taxTotal: 'taxTotal',
  total: 'total',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SaleItemScalarFieldEnum = {
  id: 'id',
  saleId: 'saleId',
  productId: 'productId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discount: 'discount',
  lineTotal: 'lineTotal',
  performedById: 'performedById',
  commissionPercentApplied: 'commissionPercentApplied'
};

exports.Prisma.SalePaymentScalarFieldEnum = {
  id: 'id',
  saleId: 'saleId',
  amount: 'amount',
  method: 'method',
  paidAt: 'paidAt',
  reference: 'reference',
  bankId: 'bankId',
  attachmentUrl: 'attachmentUrl'
};

exports.Prisma.ExpenseCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parentId: 'parentId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  taxId: 'taxId',
  email: 'email',
  phone: 'phone',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  createdById: 'createdById',
  categoryId: 'categoryId',
  supplierId: 'supplierId',
  description: 'description',
  invoiceNo: 'invoiceNo',
  attachment: 'attachment',
  currency: 'currency',
  amount: 'amount',
  paymentMethod: 'paymentMethod',
  bankId: 'bankId',
  reference: 'reference',
  incurredAt: 'incurredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExpenseItemScalarFieldEnum = {
  id: 'id',
  expenseId: 'expenseId',
  categoryId: 'categoryId',
  description: 'description',
  quantity: 'quantity',
  unitAmount: 'unitAmount',
  taxPercent: 'taxPercent',
  lineTotal: 'lineTotal'
};

exports.Prisma.PurchaseScalarFieldEnum = {
  id: 'id',
  purchaseNumber: 'purchaseNumber',
  supplierId: 'supplierId',
  currency: 'currency',
  invoiceNo: 'invoiceNo',
  status: 'status',
  note: 'note',
  paymentMethod: 'paymentMethod',
  bankId: 'bankId',
  reference: 'reference',
  subtotal: 'subtotal',
  taxTotal: 'taxTotal',
  total: 'total',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseItemScalarFieldEnum = {
  id: 'id',
  purchaseId: 'purchaseId',
  productId: 'productId',
  quantity: 'quantity',
  unitCost: 'unitCost',
  lineTotal: 'lineTotal'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  moveType: 'moveType',
  quantity: 'quantity',
  unitCost: 'unitCost',
  refType: 'refType',
  refId: 'refId',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.AccountsReceivableScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  saleId: 'saleId',
  currency: 'currency',
  total: 'total',
  balance: 'balance',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountsReceivablePaymentScalarFieldEnum = {
  id: 'id',
  receivableId: 'receivableId',
  amount: 'amount',
  paidAt: 'paidAt',
  method: 'method',
  note: 'note',
  bankId: 'bankId'
};

exports.Prisma.PayrollEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kind: 'kind',
  description: 'description',
  currency: 'currency',
  amount: 'amount',
  period: 'period',
  runId: 'runId',
  createdAt: 'createdAt'
};

exports.Prisma.PayrollRunScalarFieldEnum = {
  id: 'id',
  periodType: 'periodType',
  periodLabel: 'periodLabel',
  startDate: 'startDate',
  endDate: 'endDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PayrollRunItemScalarFieldEnum = {
  id: 'id',
  runId: 'runId',
  userId: 'userId',
  commissionsTotal: 'commissionsTotal',
  advancesTotal: 'advancesTotal',
  adjustmentsTotal: 'adjustmentsTotal',
  salaryFixed: 'salaryFixed',
  payableTotal: 'payableTotal',
  paidAmount: 'paidAmount',
  balance: 'balance',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankTransactionScalarFieldEnum = {
  id: 'id',
  bankId: 'bankId',
  type: 'type',
  amount: 'amount',
  description: 'description',
  reference: 'reference',
  transactionDate: 'transactionDate',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  salePaymentId: 'salePaymentId',
  receivablePaymentId: 'receivablePaymentId',
  expenseId: 'expenseId',
  purchaseId: 'purchaseId',
  relatedBankId: 'relatedBankId',
  transferPairId: 'transferPairId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ProductType = exports.$Enums.ProductType = {
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  TRANSFER: 'TRANSFER',
  DIGITAL: 'DIGITAL',
  OTHER: 'OTHER'
};

exports.PurchaseStatus = exports.$Enums.PurchaseStatus = {
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  RECEIVED: 'RECEIVED',
  CLOSED: 'CLOSED',
  CANCELED: 'CANCELED'
};

exports.StockMoveType = exports.$Enums.StockMoveType = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.AccountsReceivableStatus = exports.$Enums.AccountsReceivableStatus = {
  OPEN: 'OPEN',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  CANCELED: 'CANCELED'
};

exports.PayrollEntryKind = exports.$Enums.PayrollEntryKind = {
  COMMISSION: 'COMMISSION',
  ADVANCE: 'ADVANCE',
  ADJUSTMENT: 'ADJUSTMENT',
  PAYMENT: 'PAYMENT'
};

exports.PayrollPeriodType = exports.$Enums.PayrollPeriodType = {
  DAILY: 'DAILY',
  BIWEEKLY: 'BIWEEKLY',
  CUSTOM: 'CUSTOM'
};

exports.PayrollRunStatus = exports.$Enums.PayrollRunStatus = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
  PAID: 'PAID'
};

exports.BankTransactionType = exports.$Enums.BankTransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER_OUT: 'TRANSFER_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Customer: 'Customer',
  Bank: 'Bank',
  ProductCategory: 'ProductCategory',
  Product: 'Product',
  Sale: 'Sale',
  SaleItem: 'SaleItem',
  SalePayment: 'SalePayment',
  ExpenseCategory: 'ExpenseCategory',
  Supplier: 'Supplier',
  Expense: 'Expense',
  ExpenseItem: 'ExpenseItem',
  Purchase: 'Purchase',
  PurchaseItem: 'PurchaseItem',
  StockMovement: 'StockMovement',
  AccountsReceivable: 'AccountsReceivable',
  AccountsReceivablePayment: 'AccountsReceivablePayment',
  PayrollEntry: 'PayrollEntry',
  PayrollRun: 'PayrollRun',
  PayrollRunItem: 'PayrollRunItem',
  BankTransaction: 'BankTransaction'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
